############################################################################### 
# Author: Agustin Bassi 
# Date: July 2020 
# Copyright: Agustin Bassi
# Project: MQ-Connection
# Brief: TODO: Describe it 
#
# To attach to mosquitto clients running into mosquitto container run:
#
#   - docker exec -it mosquitto mosquitto_sub -t "#"
#   - docker exec -it mosquitto mosquitto_pub -t "greet" "hello mq-connection"
#
###############################################################################
  
version: '3'

services:

  mosquitto:
    # service header
    image:                  eclipse-mosquitto:latest
    hostname:               mosquitto
    container_name:         mosquitto
    # project labels 
    labels: 
      project:              "MQ Connection" 
      day:                  "Jul 2020" 
      mantainer:            Agustin Bassi
    # service specific settings
    volumes:
      -                     ./mqtt-broker/config:/mosquitto/config
      # -                     ./mqtt-broker/certs:/mosquitto/certs
    networks:
      -                     mq-connection-network 
    expose:
      -                     "1883"
      -                     "8883"
      -                     "9001"
    ports:
      -                     "1883:1883"
      -                     "8883:8883"
      -                     "9001:9001"

  web-client:
    # service header
    image:                  httpd:2.4
    hostname:               web-client
    container_name:         web-client
    # project labels 
    labels: 
      project:              "MQ Connection" 
      day:                  "Jul 2020" 
      mantainer:            Agustin Bassi
    # service specific settings
    volumes:
        -                   ./mqtt-client-web:/usr/local/apache2/htdocs/
    networks:
      -                     mq-connection-network 
    ports:
      -                     "5001:80"


networks:
  mq-connection-network:
    driver:                 bridge